//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Racer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highscores
    {
        public int ID { get; set; }
        public string Nick { get; set; }
        public string Czas { get; set; }
        public int Wynik { get; set; }
        public int Punkty_kontr { get; set; }
        public string Data { get; set; }
    }
}
